blank_issues_enabled: true
contact_links:
  - name: Questions / General Discussion
    url: https://github.com/neotranscript/core/discussions
    about: Please ask questions and discuss ideas in Discussions
